<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KR2Q4MNQ" ignored="1" name="Default test(failed)" tests="1" failures="1" timestamp="10 Feb 2018 06:12:20 GMT" time="3.108" errors="0">
  <testcase name="failtest" time="3.075" classname="testngdemo.timeoutdemo">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngdemo.timeoutdemo.failtest() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngdemo.timeoutdemo.failtest() didn't finish within the time-out 3000at testngdemo.timeoutdemo.failtest(timeoutdemo.java:16)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- failtest -->
  <testcase name="passtest" time="0.0" classname="testngdemo.timeoutdemo">
    <ignored/>
  </testcase> <!-- passtest -->
</testsuite> <!-- Default test(failed) -->
