<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-KR2Q4MNQ" name="testngdemo.timeoutdemo" tests="1" failures="0" timestamp="10 Feb 2018 06:12:20 GMT" time="3.075" errors="1">
  <testcase name="failtest" time="3.075" classname="testngdemo.timeoutdemo">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngdemo.timeoutdemo.failtest() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngdemo.timeoutdemo.failtest() didn't finish within the time-out 3000at testngdemo.timeoutdemo.failtest(timeoutdemo.java:16)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- failtest -->
</testsuite> <!-- testngdemo.timeoutdemo -->
